### ISSUE TITLE
500 Error on Post to Cookies

### ISSUE THREAD

**Issue by lipovac** [eigenfoo/euphoria#64]
@wside 

```

Wed Apr 17 19:12:12 EDT 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[qtp88646218-16] WARN com.spotify.apollo.dispatch.EndpointInvocationHandler - Got Exception : "id" when invoking endpoint for request: RequestValue{method=POST, uri=/api/cookie, parameters={}, service=Optional.empty, payload=Optional[ByteString[size=48 md5=a79f79d9706dd146213197c671bc5345]], internalHeadersImpl=Headers{entries=[User-Agent=curl/7.61.0, Host=localhost:8080, Accept=*/*, Content-Length=48, Content-Type=application/json]}, ttl=Optional.empty}
java.lang.NullPointerException: id
	at edu.cooper.ece366.euphoria.CookieBuilder$Value.<init>(CookieBuilder.java:87)
	at edu.cooper.ece366.euphoria.CookieBuilder$Value.<init>(CookieBuilder.java:77)
	at edu.cooper.ece366.euphoria.CookieBuilder.build(CookieBuilder.java:66)
	at edu.cooper.ece366.euphoria.CookieHandlers.createCookie(CookieHandlers.java:99)
	at com.spotify.apollo.route.Middleware.lambda$syncToAsync$1(Middleware.java:44)
	at com.spotify.apollo.route.JsonSerializerMiddlewares.lambda$null$1(JsonSerializerMiddlewares.java:64)
	at com.spotify.apollo.route.AsyncHandler.lambda$flatMapSync$4(AsyncHandler.java:92)
	at edu.cooper.ece366.euphoria.CookieHandlers.lambda$null$2(CookieHandlers.java:114)
	at com.spotify.apollo.route.RouteEndpoint.invoke(RouteEndpoint.java:61)
	at com.spotify.apollo.dispatch.EndpointInvocationHandler.handle(EndpointInvocationHandler.java:56)
	at com.spotify.apollo.dispatch.EndpointInvocationHandler.lambda$create$0(EndpointInvocationHandler.java:47)
	at com.spotify.apollo.request.RequestHandlerImpl.handleEndpointMatch(RequestHandlerImpl.java:95)
	at com.spotify.apollo.request.RequestRunnableImpl.matchAndRun(RequestRunnableImpl.java:112)
	at com.spotify.apollo.request.RequestRunnableImpl.run(RequestRunnableImpl.java:70)
	at com.spotify.apollo.request.RequestHandlerImpl.handle(RequestHandlerImpl.java:65)
	at com.spotify.apollo.http.server.ApolloRequestHandler.handle(ApolloRequestHandler.java:85)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:539)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)
[qtp88646218-16] INFO com.spotify.apollo.http.server.CombinedFormatLogger - 127.0.0.1 - - [17/Apr/2019:19:12:12 -0400] "POST /api/cookie" 500 - "-" "curl/7.61.0"

```

**Comment by lipovac** [comment]
It creates a cookie in the table with the proper id and isUser value but doesnt return anything on curl post. 

curl GET of the cookie value does work and does return properly.
